GET http://localhost:8080

###

// The request body is provided in place
POST http://localhost:8080/login
Content-Type: application/json

{ "email" : "test@email.com", "password": "bla" }


###
GET http://localhost:8080/auth-test
Authorization: "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJodHRwOi8vMC4wLjAuMDo4MDgwL3RyYW5zY3JpYmUiLCJpc3MiOiJodHRwOi8vMC4wLjAuMDo4MDgwLyIsImV4cCI6MTY0MzY0NjU5MiwiZW1haWwiOiJ0ZXN0QGVtYWlsLmNvbSJ9.r3Tuc5m6Ol3PIVy4AwokFF4fiOVizOsFMfKPhssE-9A"


###
POST http://localhost:8080/login
Content-Type: application/json

{
  "email": "test@email.com",
  "password": "bla"
}


###
GET http://localhost:8080/auth-test
Authorization: Bearer {{auth_token}}